#!/bin/bash
. /etc/lsb-release
echo "Checking Ubuntu Version --code made for 20.04 release"

if [ $ID = "Ubuntu" ]
then
	if [ $DISTRIB_RELEASE = "20.04" ]
	then
	echo "yep, legit, script will run now"
else
	echo "nope, distro or version are wrong, make sure it's Ubuntu 20.04"
	echo "Your distro is: $ID , $DISTRIB_RELEASE"
	exit 1
fi

if [ ! "' ping -c 1 google.com'" ]
then
	echo "you're offline-- cant proceed"
	exit 1
fi

execute () {
echo "$ $*"
OUTPUT=$($@ 2>&1)
if [ $? -ne 0 ]; then
	echo "$OUTPUT"
echo ""
	echo "Failed to Execute $*" >&2
	exit 1
fi
}
execute sudo apt-get update -y
execute sudo apt-get upgrade -y
execute sudo apt-get install ubuntu-restricted-extras -y
execute sudo apt-get install vim -y

# creating vim tree and copying personal vim config file
mkdir -p ~/.vim ~/.vim/autoload ~/.vim/backup ~/.vim/colors ~/.vim/plugged
cp ./vimrc.local/ ~/.vim/

#downloading system themes
execute sudo apt install gnome-tweaks -y
execute sudo apt install numix-icon-theme-circle -y

#setting ssytem themes
gsettings set org.gnome.desktop.interface icon-theme 'numix-icon-theme-circle'
