#!/bin/bash
./etc/lsb-release
echo "Checking Ubuntu Version --code made for 20.04 release"

if [ $DISTRIB_ID = "Ubuntu" ]
then
	if [ $DISTRIB_RELEASE = "20.04" ]
	then
	echo "yep, legit, script will run now"
	fi
else
	echo "nope, distro or version are wrong, make sure it's Ubuntu 20.04"
	echo "Your distro is: $ID , $DISTRIB_RELEASE"
	exit 1
fi

if [ ! "' ping -c 1 google.com'" ]
then
	echo "you're offline-- cant proceed"
	exit 1
fi

#error catching and printing function
execute () {
echo "$ $*"
OUTPUT=$($@ 2>&1)
if [ $? -ne 0 ]; then
	echo "$OUTPUT"
echo ""
	echo "Failed to Execute $*" >&2
	exit 1
fi
}


execute sudo apt-get update -y
execute sudo apt-get upgrade -y
execute sudo apt-get install ubuntu-restricted-extras -y
execute sudo apt-get install vim -y
execute sudo apt-get install neofetch -y
execute sudo apt-get install gnome-tweaks -y
execute sudo apt-get install hollywood -y
execute sudo apt-get install gnome-shell-extensions -y


# creating vim tree and copying personal vim config file
execute sudo cp ./vimrc.local/ /etc/vim/

#downloading system themes
execute sudo apt install numix-icon-theme-circle -y

#setting sytem themes
execute gsettings set org.gnome.desktop.interface icon-theme 'Numix-Circle'
execute gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-Dark'

#users prompts
#how many
echo "Ile uzytkownikow chcesz stworzyc"
read ilosc
if [ $ilosc != 0 ]
then
echo "Wprowadz prefix uzytkownika"
read prefix
num=0
while [ $num != $ilosc ]
do
	execute sudo useradd -m $prefix$num
	execute $passwd | passwd $username $prefix$num
	$num++
done
else
echo ""
fi

clear
neofetch 
